import React, { useState } from 'react';
import { useSimulation } from '../../context/SimulationContext';
import {
  TrendingUp,
  CloudRain,
  Waves,
  AlertTriangle,
  Hospital,
  Home,
  Clock,
  ShieldAlert,
  BarChart3,
  Calendar
} from 'lucide-react';

export const ForecastView: React.FC = () => {
  const { forecastSeries, zones, kpis } = useSimulation();
  const [selectedMetric, setSelectedMetric] = useState<'incidents' | 'water' | 'medical' | 'shelter'>('incidents');

  // Find peak values
  const peakIncident = Math.max(...forecastSeries.map((f) => f.incidentVolume));
  const peakWater = Math.max(...forecastSeries.map((f) => f.waterLevelM));
  const peakShelter = Math.max(...forecastSeries.map((f) => f.shelterOccupancyPercent));
  const peakHospital = Math.max(...forecastSeries.map((f) => f.hospitalCapacityStressPercent));

  return (
    <div className="flex-1 p-6 space-y-6 overflow-y-auto bg-[#070b14] text-slate-200">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-4">
        <div>
          <div className="flex items-center gap-2">
            <TrendingUp className="w-5 h-5 text-cyan-400" />
            <h1 className="text-xl font-mono font-black text-white uppercase tracking-wider">
              PREDICTIVE FORECAST & DEMAND MODELING
            </h1>
          </div>
          <p className="text-xs text-slate-400 font-mono mt-1">
            Catchment runoff projections &bull; 6-hour demand forecasting &bull; Capacity threshold warnings
          </p>
        </div>

        <div className="flex items-center gap-2 font-mono text-xs">
          <span className="px-3 py-1 rounded bg-rose-500/10 border border-rose-500/30 text-rose-400 flex items-center gap-1.5">
            <AlertTriangle className="w-3.5 h-3.5" />
            <span>Peak Demand Anticipated at T+3h</span>
          </span>
        </div>
      </div>

      {/* Summary KPI Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 font-mono">
        <div className="bg-slate-900/80 border border-slate-800 p-5 rounded-xl shadow-lg">
          <div className="flex items-center justify-between text-xs text-slate-400">
            <span className="uppercase">Peak Incident Rate</span>
            <AlertTriangle className="w-4 h-4 text-rose-400" />
          </div>
          <div className="text-3xl font-black text-white mt-2">{peakIncident} / hr</div>
          <div className="text-[11px] text-rose-400 mt-1 font-bold">
            +69% increase from current baseline
          </div>
        </div>

        <div className="bg-slate-900/80 border border-slate-800 p-5 rounded-xl shadow-lg">
          <div className="flex items-center justify-between text-xs text-slate-400">
            <span className="uppercase">Max River Crest</span>
            <Waves className="w-4 h-4 text-blue-400" />
          </div>
          <div className="text-3xl font-black text-blue-400 mt-2">{peakWater.toFixed(1)} m</div>
          <div className="text-[11px] text-amber-400 mt-1">
            +0.9m above official Danger Mark (4.8m)
          </div>
        </div>

        <div className="bg-slate-900/80 border border-slate-800 p-5 rounded-xl shadow-lg">
          <div className="flex items-center justify-between text-xs text-slate-400">
            <span className="uppercase">Peak Shelter Stress</span>
            <Home className="w-4 h-4 text-amber-400" />
          </div>
          <div className="text-3xl font-black text-amber-300 mt-2">{peakShelter}%</div>
          <div className="text-[11px] text-amber-400 mt-1">
            Town Hall Pavilion near 100% saturation
          </div>
        </div>

        <div className="bg-slate-900/80 border border-slate-800 p-5 rounded-xl shadow-lg">
          <div className="flex items-center justify-between text-xs text-slate-400">
            <span className="uppercase">Hospital ICU Strain</span>
            <Hospital className="w-4 h-4 text-purple-400" />
          </div>
          <div className="text-3xl font-black text-purple-300 mt-2">{peakHospital}%</div>
          <div className="text-[11px] text-purple-400 mt-1">
            Apex Trauma Center approaching redline
          </div>
        </div>
      </div>

      {/* Main Forecast Curve Visualizer */}
      <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 shadow-lg font-mono text-xs space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800 pb-3">
          <div>
            <span className="font-bold text-white uppercase tracking-wider block">
              Multi-Hour Predictive Trajectory (Past -3h &rarr; Future +6h)
            </span>
            <span className="text-[11px] text-slate-400">
              Generated by Hydrological Hydrograph & Distress Call Density Modeling
            </span>
          </div>

          {/* Metric Selector Tabs */}
          <div className="flex items-center gap-1.5 bg-slate-950 p-1 rounded-lg border border-slate-800">
            <button
              onClick={() => setSelectedMetric('incidents')}
              className={`px-3 py-1 rounded text-[11px] font-bold transition ${
                selectedMetric === 'incidents' ? 'bg-cyan-600 text-white' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Incidents
            </button>
            <button
              onClick={() => setSelectedMetric('water')}
              className={`px-3 py-1 rounded text-[11px] font-bold transition ${
                selectedMetric === 'water' ? 'bg-blue-600 text-white' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              River Crest
            </button>
            <button
              onClick={() => setSelectedMetric('shelter')}
              className={`px-3 py-1 rounded text-[11px] font-bold transition ${
                selectedMetric === 'shelter' ? 'bg-amber-600 text-white' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Shelter Load
            </button>
            <button
              onClick={() => setSelectedMetric('medical')}
              className={`px-3 py-1 rounded text-[11px] font-bold transition ${
                selectedMetric === 'medical' ? 'bg-purple-600 text-white' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Hospital Bed Stress
            </button>
          </div>
        </div>

        {/* Chart Canvas Area */}
        <div className="h-64 flex items-end gap-3 pt-6 pb-2 border-b border-slate-800/80 relative">
          {/* Threshold watermark line for selected metric */}
          {selectedMetric === 'water' && (
            <div
              className="absolute left-0 right-0 border-b border-dashed border-rose-500/80 z-10 pointer-events-none"
              style={{ bottom: `${(4.8 / 6.0) * 100}%` }}
            >
              <span className="absolute right-2 -top-4 text-[9px] font-bold text-rose-400 bg-slate-950 px-1.5 py-0.5 rounded border border-rose-800/60">
                OFFICIAL DANGER LEVEL (4.8m)
              </span>
            </div>
          )}

          {forecastSeries.map((point) => {
            const isNow = point.hourOffset === 'Now';
            const isFuture = point.hourOffset.startsWith('+');

            let val = point.incidentVolume;
            let maxVal = 85;
            let unit = 'inc/hr';
            let color = isFuture ? 'bg-rose-500' : 'bg-rose-700/60';

            if (selectedMetric === 'water') {
              val = point.waterLevelM;
              maxVal = 6.0;
              unit = 'm';
              color = isFuture ? 'bg-blue-500' : 'bg-blue-700/60';
            } else if (selectedMetric === 'shelter') {
              val = point.shelterOccupancyPercent;
              maxVal = 100;
              unit = '%';
              color = isFuture ? 'bg-amber-500' : 'bg-amber-700/60';
            } else if (selectedMetric === 'medical') {
              val = point.hospitalCapacityStressPercent;
              maxVal = 100;
              unit = '%';
              color = isFuture ? 'bg-purple-500' : 'bg-purple-700/60';
            }

            const heightPct = Math.round((val / maxVal) * 100);

            return (
              <div key={point.hourOffset} className="flex-1 flex flex-col items-center group relative h-full justify-end">
                {/* Confidence bound indicator for future steps */}
                {isFuture && (
                  <div
                    className="absolute w-full rounded-t bg-cyan-500/10 border-t border-cyan-400/40 pointer-events-none"
                    style={{
                      bottom: '0%',
                      height: `${Math.min(100, heightPct + 12)}%`
                    }}
                  />
                )}

                <div
                  className={`w-full rounded-t transition-all z-10 ${color} ${
                    isNow ? 'ring-2 ring-cyan-400 shadow-lg shadow-cyan-500/30' : ''
                  }`}
                  style={{ height: `${heightPct}%` }}
                />

                <span className="text-[11px] font-bold text-white mt-1 z-10">{val}{unit}</span>
                <span className={`text-[10px] ${isNow ? 'text-cyan-400 font-black' : 'text-slate-400'}`}>
                  {point.hourOffset}
                </span>

                {/* Tooltip */}
                <div className="absolute bottom-full mb-2 hidden group-hover:flex flex-col items-center z-30 pointer-events-none">
                  <div className="bg-slate-950 border border-slate-700 px-2.5 py-1.5 rounded text-[11px] text-slate-200 whitespace-nowrap shadow-xl">
                    <p className="font-bold text-white">{point.hourOffset === 'Now' ? 'Current Observation' : `Forecast: ${point.hourOffset}`}</p>
                    <p className="text-rose-400">Incidents: {point.incidentVolume} / hr</p>
                    <p className="text-blue-300">River Level: {point.waterLevelM} m</p>
                    <p className="text-amber-300">Shelter Load: {point.shelterOccupancyPercent}%</p>
                    <p className="text-purple-300">Hospital Stress: {point.hospitalCapacityStressPercent}%</p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        <div className="flex items-center justify-between text-[11px] text-slate-400 pt-1">
          <span>&larr; Historical Observations (Pre-incident baseline)</span>
          <span className="text-cyan-400 font-bold">&bull; Real-time Sensor Ingestion &bull;</span>
          <span className="text-rose-400 font-bold">Projected Peak & Recession Horizon &rarr;</span>
        </div>
      </div>

      {/* Recommended Pre-Emptive Actions Based on Forecast */}
      <div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 shadow-lg font-mono text-xs space-y-4">
        <div className="flex items-center justify-between border-b border-slate-800 pb-2.5">
          <span className="font-bold text-white uppercase tracking-wider flex items-center gap-2">
            <ShieldAlert className="w-4 h-4 text-amber-400" />
            <span>Pre-Emptive Action Directives (Horizon +1h to +3h)</span>
          </span>
          <span className="text-[10px] text-emerald-400">3 STRATEGIC WINDOWS OPEN</span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="p-4 rounded-lg bg-slate-950/70 border border-amber-500/30 space-y-2">
            <div className="flex items-center justify-between">
              <span className="font-bold text-amber-400 text-xs">WINDOW 1: T+01h</span>
              <span className="px-1.5 py-0.5 rounded bg-amber-500/20 text-amber-300 text-[10px]">URGENT</span>
            </div>
            <div className="font-bold text-white text-xs">Stage 4 Secondary Medical Units at Central Depot</div>
            <p className="text-slate-400 text-[11px] font-sans">
              Before Eastern levee overtopping impedes arterial bypass, stage mobile trauma units closer to Sector 6 access nodes.
            </p>
          </div>

          <div className="p-4 rounded-lg bg-slate-950/70 border border-rose-500/30 space-y-2">
            <div className="flex items-center justify-between">
              <span className="font-bold text-rose-400 text-xs">WINDOW 2: T+02h</span>
              <span className="px-1.5 py-0.5 rounded bg-rose-500/20 text-rose-300 text-[10px]">CRITICAL</span>
            </div>
            <div className="font-bold text-white text-xs">Divert Non-Critical Patients Away from Apex Trauma</div>
            <p className="text-slate-400 text-[11px] font-sans">
              Forecast models project Apex Trauma Center exceeding 95% bed capacity by 18:00. Reroute moderate patients to South General.
            </p>
          </div>

          <div className="p-4 rounded-lg bg-slate-950/70 border border-cyan-500/30 space-y-2">
            <div className="flex items-center justify-between">
              <span className="font-bold text-cyan-400 text-xs">WINDOW 3: T+03h</span>
              <span className="px-1.5 py-0.5 rounded bg-cyan-500/20 text-cyan-300 text-[10px]">PRECAUTIONARY</span>
            </div>
            <div className="font-bold text-white text-xs">Open Secondary Shelter at North High School</div>
            <p className="text-slate-400 text-[11px] font-sans">
              Town Hall Pavilion shelter will hit capacity limit (1,200). Activate secondary facility to prevent overflow crowding.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
